// ===========================
// Placas PVC - Marble Sheets
// Generado a partir de las imágenes en la carpeta 'img/'
// Tamaño: 1220 x 2440 mm, espesor: 3mm, density: 2000kg/m3
// ===========================
const productosDB = [
  {
    id: 'pvc_blanco',
    nombre: 'Blanco Liso',
    ref: 'PVC-M-001',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy', 'Matte', 'Skin feel', 'High glossy', 'Embossed stone', '3D printing'],
    filmOptions: ['Heat transfer film', 'PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Hotel','Restaurant','Hospital','School','Mall'],
    acabado: 'Blanco liso, aspecto clásico',
    imagen: 'img/blanco.png',
    galeria: ['img/blanco.png']
  },
  {
    id: 'pvc_carrara_golden',
    nombre: 'Carrara Golden',
    ref: 'PVC-M-002',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','High glossy','Embossed stone'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Hotel','Restaurant','Mall'],
    acabado: 'Mármol Carrara con vetas doradas',
    imagen: 'img/carrara-golden.jpg',
    galeria: ['img/carrara-golden.jpg']
  },
  {
    id: 'pvc_carrara_goldend',
    nombre: 'Carrara Golden D',
    ref: 'PVC-M-003',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','High glossy'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Hotel','Restaurant'],
    acabado: 'Variación Carrara con vetas doradas intensas',
    imagen: 'img/carrara-goldend.jpg',
    galeria: ['img/carrara-goldend.jpg']
  },
  {
    id: 'pvc_madera_oscura',
    nombre: 'Madera Oscura',
    ref: 'PVC-M-004',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Matte','Skin feel'],
    filmOptions: ['PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Restaurant','Mall'],
    acabado: 'Efecto madera en tono oscuro, ideal para muebles y revestimientos',
    imagen: 'img/madera-oscura.jpg',
    galeria: ['img/madera-oscura.jpg']
  },
  {
    id: 'pvc_marquina',
    nombre: 'Marquina',
    ref: 'PVC-M-005',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','High glossy'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Hotel','Restaurant','Home'],
    acabado: 'Mármol marquina, fondo oscuro con vetas claras',
    imagen: 'img/marquina.jpeg',
    galeria: ['img/marquina.jpeg']
  },
  {
    id: 'pvc_travertino',
    nombre: 'Travertino',
    ref: 'PVC-M-006',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Matte','Embossed stone'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Hotel','Restaurant'],
    acabado: 'Textura travertino, tacto natural',
    imagen: 'img/travertino.jpg',
    galeria: ['img/travertino.jpg']
  },
  {
    id: 'pvc_wpf_04',
    nombre: 'WPF-04',
    ref: 'PVC-M-007',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','3D printing'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Mall','Hotel','Home'],
    acabado: 'Estampa WPF-04, diseño marmoleado moderno',
    imagen: 'img/WPF-04.jpg',
    galeria: ['img/WPF-04.jpg']
  },
  {
    id: 'pvc_wpf_06',
    nombre: 'WPF-06',
    ref: 'PVC-M-008',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','High glossy'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Restaurant'],
    acabado: 'Estampa WPF-06, veteado suave',
    imagen: 'img/WPF-06.jpg',
    galeria: ['img/WPF-06.jpg']
  },
  {
    id: 'pvc_wpf_08',
    nombre: 'WPF-08',
    ref: 'PVC-M-009',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','Matte'],
    filmOptions: ['Heat transfer film','PVC Film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Hotel','Hospital','School'],
    acabado: 'Estampa WPF-08, patrón marmoleado claro',
    imagen: 'img/WPF-08.jpg',
    galeria: ['img/WPF-08.jpg']
  },
  {
    id: 'pvc_wpf_10',
    nombre: 'WPF-10',
    ref: 'PVC-M-010',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['High glossy','Skin feel'],
    filmOptions: ['PVC Film','Heat transfer film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Mall'],
    acabado: 'Estampa WPF-10, aspecto premium',
    imagen: 'img/WPF-10.jpg',
    galeria: ['img/WPF-10.jpg']
  },
  {
    id: 'pvc_wpf_17',
    nombre: 'WPF-17',
    ref: 'PVC-M-011',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Matte','Embossed stone'],
    filmOptions: ['PVC Film','Heat transfer film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Hotel','Restaurant'],
    acabado: 'Estampa WPF-17, textura natural',
    imagen: 'img/WPF-17.jpg',
    galeria: ['img/WPF-17.jpg']
  },
  {
    id: 'pvc_wpf_18',
    nombre: 'WPF-18',
    ref: 'PVC-M-012',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Mirror glossy','High glossy'],
    filmOptions: ['PVC Film','Heat transfer film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Hotel','Restaurant'],
    acabado: 'Estampa WPF-18, vetas marcadas',
    imagen: 'img/WPF-18.jpg',
    galeria: ['img/WPF-18.jpg']
  },
  {
    id: 'pvc_wpf_19',
    nombre: 'WPF-19',
    ref: 'PVC-M-013',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['Skin feel','Matte'],
    filmOptions: ['PVC Film','Heat transfer film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Home','Hospital','School'],
    acabado: 'Estampa WPF-19, acabado suave',
    imagen: 'img/WPF-19.jpg',
    galeria: ['img/WPF-19.jpg']
  },
  {
    id: 'pvc_wpf_20',
    nombre: 'WPF-20',
    ref: 'PVC-M-014',
    categoria: 'PVC Marble Sheet',
    size: '1220x2440 mm',
    thickness_mm: 3,
    density_kg_m3: 2000,
    surfaceOptions: ['High glossy','3D printing'],
    filmOptions: ['PVC Film','Heat transfer film'],
    material: 'PVC + Calcium powder',
    aplicaciones: ['Mall','Restaurant','Hotel'],
    acabado: 'Estampa WPF-20, diseño marmoleado elegante',
    imagen: 'img/WPF-20.jpg',
    galeria: ['img/WPF-20.jpg']
  }
];

// Si querés integrarlos a tu productosDB existente:
// productosDB.push(...pvcMarbleSheets);

// O para reemplazar por completo (si querés que el DB sean solo estas placas):
// productosDB = pvcMarbleSheets;
